export const GET_CATEGORY = "GET_CATEGORY";
export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const ADD_NEW_CATEGORY_FIELD = "ADD_NEW_CATEGORY_FIELD";
export const UPDATE_CATEGORY_FIELD = "UPDATE_CATEGORY_FIELD";
export const DELETE_CATEGORY_FIELD = "DELETE_CATEGORY_FIELD";

export const ADD_NEW_CATEGORY_FIELDS_ITEM = "ADD_NEW_CATEGORY_FIELDS_ITEM";
